
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

inhibit_all_warnings!

use_frameworks!

platform :ios, '9.0'

target 'CyweeBleSDK-iOS_Example' do
  pod 'CyweeBleSDK-iOS', :path => '../'
  pod 'YYKit'
  pod 'Masonry'
  pod 'Toast'
  pod 'MBProgressHUD'
end
